### ISSUE TITLE
I can't install it on docker.io/nodered/node-red:1.3.1-12 docker image

### ISSUE THREAD

**Issue by athern27** [jatu-studiobox/node-red-contrib-ui-widget-bulb-basic#2]
My docker version is 
Docker version 1.13.1, build 7d71120/1.13.1

I can't update it as I am not the administrator
I have also tried 
npm install @studiobox/node-red-contrib-ui-widget-bulb-basic
but it also isn't working.

Pls help in this matter.

**Comment by jatu-studiobox** [comment]
First, sorry for lately reply. 

I am not sure about update, but in my opinion, you must have administrator role for update.

**Comment by athern27** [comment]
Yes, I figured it out. I had to update the docker image to docker.io/nodered/node-red:3.0.1-1-14 to get it start working. I think it had something to do with npm and node.js version in the docker
